<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<div class="checkout-success">
<?php $mensaje = $block->one(); echo $mensaje;?>
<h1>Hola otra vez FUERA DEL DIV</h1>
    

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Seguir comprando') ?></span></a>
        </div>
    </div>    
</div>





